### PR TITLE
Update Makefile

### PR DESCRIPTION
**Pull request by op01**

### CODE REVIEW

**Comment by suvojit-0x55aa** [comment]
Thank you for your time @op01.
But can u make the `Makefile` generic so that it targets the files we'll add eventually

**Comment by op01** [comment]
You can add your files manually by adding line

```
OBJ = FIFOPolicy.o \
     lRUpolicy.o \
     ...
```

**Comment by suvojit-0x55aa** [comment]
@op01 thank you again, but we actually don't need to change the directory of the make file. We should keep it in the root directory. Also some checks are failing if you don't mind will you please look into it

**Comment by op01** [comment]
Is everything okay?

**Comment by suvojit-0x55aa** [comment]
@op01 Sorry, But I'll have to close this pull request. Still thanks for your contribution. And if you dont mind you can take a look at other issues.

**Pull request closed without merging**
